In [12]:
# tao mang 1 chieu
import numpy as np
x1=[1,2,3,4]
x2=(1,2,3,4)
array_1=np.array(x2)
type(array_1)

numpy.ndarray

In [25]:
a1=np.zeros(5,dtype='i8')
a1

array([0, 0, 0, 0, 0], dtype=int64)

In [23]:
a2=np.ones(5)
a2

array([1., 1., 1., 1., 1.])

In [34]:
b1=np.arange(40,20,-2,dtype=float)
b1

array([40., 38., 36., 34., 32., 30., 28., 26., 24., 22.])

In [33]:
b2=np.linspace(1,10,9, dtype=int)
b2

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [35]:
print(array_1)

[1 2 3 4]


In [38]:
print(array_1.shape[0])

4


In [39]:
x=[1,2,3,4,3,5,3,2,7,8,9,9]
x1=np.array(x)
x1

array([1, 2, 3, 4, 3, 5, 3, 2, 7, 8, 9, 9])

In [40]:
x1[1]

2

In [45]:
x1

array([1, 2, 3, 4, 3, 5, 3, 2, 7, 8, 9, 9])

In [49]:
x1=np.append(x1,(123,567))
x1

array([  1,   2,   3,   4,   3,   5,   3,   2,   7,   8,   9,   9, 123,
       123, 567])

In [51]:
x1=np.insert(x1,1,888)
x1

array([999, 888,   1,   2,   3,   4,   3,   5,   3,   2,   7,   8,   9,
         9, 123, 123, 567])

In [54]:
x1=np.delete(x1,0)
x1

array([  2,   3,   4,   3,   5,   3,   2,   7,   8,   9,   9, 123, 123,
       567])

In [56]:
male=np.array([1,2,3,4])
female=np.array([-1,-2,-3,-4])
cong=male+female
cong

array([0, 0, 0, 0])

In [57]:
tru=male-female
tru

array([2, 4, 6, 8])

In [59]:
nhan=male*female
nhan

array([ -1,  -4,  -9, -16])

In [61]:
chia=male/female
chia

array([-1., -1., -1., -1.])

In [62]:
print(np.amax(male))


4


In [63]:
print(np.amin(male))

1


In [70]:
print(male.median())

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [67]:
female

array([-1, -2, -3, -4])

In [68]:
print(np.sort(female))

[-4 -3 -2 -1]


In [74]:
test=np.where(male>2)
print(test)

(array([2, 3], dtype=int64),)


In [76]:
x=np.extract(male>2,male)
x

array([3, 4])

In [89]:
import numpy as np
chieu=np.array([[1,2,3],[4,5,6]])
type(chieu)

numpy.ndarray

In [93]:
print(chieu.shape)

(2, 3)


In [1]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[-1,-2,-3],[-4,-5,-6]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[-1, -2, -3],
        [-4, -5, -6]]])

In [2]:
a[0,0,0]

1

In [3]:
a.shape
#2 ma tran, 2 dong trong mot ma tran, 3 phan tu trong mot dong

(2, 2, 3)

In [4]:
a.shape=(3,2,2)
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [-1, -2]],

       [[-3, -4],
        [-5, -6]]])

In [6]:
b=np.arange(24)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [9]:
b1=b.reshape(2,3,4)
b1
#2 ma tran, 3 dong, 4 cot

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
c1=b1[1,1,...]
c1

array([16, 17, 18, 19])

In [11]:
print("b1:")

b1:


In [3]:
import numpy as np
a= np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])